springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
campus:
  demo-seed: false
  session-mode: redis
  message-mode: rabbit
  storage-mode: minio
  scan-mode: clamav
  integration-mode: disabled
